version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/function"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "docker"
    directory: "/function"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
