version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/function"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/function"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"