FROM openjdk:8-jre-alpine

LABEL maintainer="Said Sef <said@saidsef.co.uk> (saidsef.co.uk/)"

ENV APACHE_TIKA_VERSION 1.26
ENV CLASSPATH "/opt/tika/tika-server.jar:/opt/tika/libs"
ENV SQLITE_JDBC 3.32.3
ENV JBIG2_IMAGEIO 3.0.3
ENV JAI_IMAGEIO_JPEG2000 1.3.0
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk/jre
ENV TIKA_SERVER_JAR /opt/tika/tika-server.jar
ENV PROMETHEUS_JMX_JAR_VERSION 0.12.0
ENV PORT ${PORT:-7071}

WORKDIR /opt/tika

COPY prometheus-jmx-config.yaml /opt/tika

# https://mvnrepository.com/artifact/org.apache.tika
RUN mkdir -p /opt/tika/libs && \
    apk add -U --no-cache curl tesseract-ocr tesseract-ocr-data-enm tesseract-ocr-data-ara && \
    curl -vSL https://apache.mirrors.nublue.co.uk/tika/tika-server-${APACHE_TIKA_VERSION}.jar -o /opt/tika/tika-server.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-core/${APACHE_TIKA_VERSION}/tika-core-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-core.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-xmp/${APACHE_TIKA_VERSION}/tika-xmp-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-xmp.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-serialization/${APACHE_TIKA_VERSION}/tika-serialization-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-serialization.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-parsers/${APACHE_TIKA_VERSION}/tika-parsers-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-parsers.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-langdetect/${APACHE_TIKA_VERSION}/tika-langdetect-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-langdetect.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-translate/${APACHE_TIKA_VERSION}/tika-translate-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-translate.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-nlp/${APACHE_TIKA_VERSION}/tika-nlp-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-nlp.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/tika/tika-dl/${APACHE_TIKA_VERSION}/tika-dl-${APACHE_TIKA_VERSION}.jar -o /opt/tika/libs/tika-dl.jar && \
    curl -vSL https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${PROMETHEUS_JMX_JAR_VERSION}/jmx_prometheus_javaagent-${PROMETHEUS_JMX_JAR_VERSION}.jar -o /opt/tika/jmx_prometheus_javaagent.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/${SQLITE_JDBC}/sqlite-jdbc-${SQLITE_JDBC}.jar -o /opt/tika/libs/sqlite-jdbc.jar && \
    curl -vSL https://repo1.maven.org/maven2/org/apache/pdfbox/jbig2-imageio/${JBIG2_IMAGEIO}/jbig2-imageio-${JBIG2_IMAGEIO}.jar -o /opt/tika/libs/levigo-jbig2-imageio.jar && \
    curl -vSL https://repo1.maven.org/maven2/com/github/jai-imageio/jai-imageio-jpeg2000/${JAI_IMAGEIO_JPEG2000}/jai-imageio-jpeg2000-${JAI_IMAGEIO_JPEG2000}.jar -o /opt/tika/libs/jai-imageio-jpeg2000.jar && \
    rm -rf /var/cache/apk/* /tmp/* && \
    chown -R nobody .

USER nobody

EXPOSE ${PORT} 7072

HEALTHCHECK --interval=30s --timeout=10s CMD curl --fail http://localhost:${PORT}/ || exit 1

CMD ["sh", "-c","/usr/bin/java -javaagent:/opt/tika/jmx_prometheus_javaagent.jar=7072:prometheus-jmx-config.yaml -cp $CLASSPATH -Djava.awt.headless=true org.apache.tika.server.TikaServerCli -spawnChild -enableUnsecureFeatures -enableFileUrl -h '*' -p $PORT"]
