---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tika-ui
  namespace: argocd
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/saidsef/faas-convert-to-text.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
