---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tika-ui
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: server=ghcr.io/saidsef/tika-convert-to-text:server-latest, ui=ghcr.io/saidsef/tika-convert-to-text:ui-latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/saidsef/faas-convert-to-text.git
    targetRevision: v2022.01
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
