apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s/deployment.yml
- k8s/hpa.yml
- k8s/service.yml
- k8s/ingress.yml

commonAnnotations:
  app.kubernetes.io/created-by: kustomizer
  cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  endpointslice.kubernetes.io/managed-by: controller
  kubernetes.io/enforce-mountable-secrets: "true"
  pod-security.kubernetes.io/audit: baseline
  pod-security.kubernetes.io/warn-version: latest

images:
- name: server
  newName: ghcr.io/saidsef/tika-document-to-text
  newTag: server-latest
- name: ui
  newName: ghcr.io/saidsef/tika-document-to-text
  newTag: ui-latest

vars:
- fieldref: {}
  name: HOST
  objref:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: tika-ui
