---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
- k8s/deployment.yml
- k8s/hpa.yml
- k8s/service.yml
- k8s/ingress.yml

images:
  - name: server
    newName: docker.io/saidsef/tika-convert-to-text
    newTag: server-latest
  - name: ui
    newName: docker.io/saidsef/tika-convert-to-text
    newTag: ui-latest

vars:
  - name: HOST
    objref:
      name: tika-ui
      kind: Ingress
      apiVersion: networking.k8s.io/v1
