apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
- k8s/deployment.yml
- k8s/hpa.yml
- k8s/service.yml
- k8s/ingress.yml

images:
- name: server
  newName: ghcr.io/saidsef/tika-convert-to-text
  newTag: server-latest
- name: ui
  newName: ghcr.io/saidsef/tika-convert-to-text
  newTag: ui-latest

vars:
- fieldref: {}
  name: HOST
  objref:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: tika-ui
