kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: tika-ui
spec:
  parentRefs:
  - kind: Gateway
    name: external-gw
    namespace: gateway-ingress
    sectionName: https
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: tika-ui
      port: 8080
