---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tika-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tika-ui
  maxReplicas: 10
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
