---
apiVersion: v1
kind: Service
metadata:
  name: tika-ui
  labels:
    app.kubernetes.io/name: tika-ui
    app.kubernetes.io/tier: frontend
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  selector:
    app.kubernetes.io/name: tika-ui
  ports:
  - name: server
    protocol: TCP
    port: 7071
    targetPort: 7071
  - name: ui
    protocol: TCP
    port: 8080
    targetPort: 8080
