---
apiVersion: v1
kind: Service
metadata:
  name: tika-ui
  labels:
    app: ui
    tier: frontend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: ui
  ports:
  - name: server-monitor
    protocol: TCP
    port: 7072
    targetPort: 7072
  - name: server
    protocol: TCP
    port: 7071
    targetPort: 7071
  - name: ui
    protocol: TCP
    port: 8080
    targetPort: 8080
