apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../k8s/nginx-ingress

commonAnnotations:
  app.kubernetes.io/created-by: kustomizer
  cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  endpointslice.kubernetes.io/managed-by: controller
  kubernetes.io/enforce-mountable-secrets: "true"
  pod-security.kubernetes.io/audit: baseline
  pod-security.kubernetes.io/warn-version: latest

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: tika-server
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/saidsef/tika-document-to-text:server-merge
- target:
    group: apps
    version: v1
    kind: Deployment
    name: tika-ui
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/saidsef/tika-document-to-text:ui-merge
- target:
    kind: Ingress
    name: tika-ui
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tika-ui-merge.saidsef.co.uk
